### ISSUE TITLE
🐛 BUG: TypeError: Astro.fetchContent is not a function

### ISSUE THREAD

**Issue by wiesson** [snowpackjs/astro#815] opened 2021-07-22 10:13 UTC
### What package manager are you using?

npm

### What operating system are you using?

MacOS 11.2.3

### Describe the Bug

I have cloned a fresh project, using the portfolio template. If I try to build the project (no changes been made), it fails:

```
$ astro git:(astro) ✗ npm run build 

> @example/portfolio@0.0.1 build
> astro build

[config] Set "buildOptions.site" to generate correct canonical URLs and sitemap
[13:12:40] [snowpack] Hint: run "snowpack init" to create a project config file. Using defaults...
[13:12:40] [snowpack] Ready!
[build] ! building pages...
[build] Unable to render src/pages/projects.astro

TypeError: Astro.fetchContent is not a function
    at file:///Users/wiese/Dev/wiesson.dev/packages/astro/src/pages/projects.astro
    at file:///Users/wiese/Dev/wiesson.dev/packages/astro/src/pages/projects.astro
    at Object.__renderPage (file:///Users/wiese/Dev/wiesson.dev/packages/astro/src/pages/projects.astro
    at load (file:///Users/wiese/Dev/wiesson.dev/packages/astro/node_modules/astro/src/runtime.ts:229:35)
    at buildStaticPage (file:///Users/wiese/Dev/wiesson.dev/packages/astro/node_modules/astro/src/build/page.ts:95:18)
    at async Promise.all (index 5)
    at build (file:///Users/wiese/Dev/wiesson.dev/packages/astro/node_modules/astro/src/build.ts:77:7)
    at buildAndExit (file:///Users/wiese/Dev/wiesson.dev/packages/astro/node_modules/astro/src/cli.ts:16:15)

[build] ✕ building pages failed!
```

### Steps to Reproduce

1. `pnpm init astro` using template `portfolio`
2.  `pnpm run build`

**Comment by FredKSchott** [comment] 2021-07-22 15:40
There's a current bug in `next` that's preventing me from confirming. But, I believe that this is fixed in `next`.

**Comment by amatiasq** [comment] 2021-07-29 12:12
This is the offending line:
https://github.com/snowpackjs/astro/blob/main/examples/portfolio/src/pages/projects.astro#L7

This happened to me when I tried to chain methods after `Astro.fetchContent()` but works if you make the call in different sentences.

```js
const projectsRaw = Astro.fetchContent('./project/*.md')
const projects = projectsRaw.filter(({ published_at }) => !!published_at)
  .sort((a, b) => new Date(b.published_at) - new Date(a.published_at));
```

I don't know why this happens but it does.

**Comment by jasikpark** [comment] 2021-07-29 21:35
What happens if you try 
```js
const projects = (Astro.fetchContent('./project/*.md')).filter(({ published_at }) => !!published_at)
  .sort((a, b) => new Date(b.published_at) - new Date(a.published_at));
```
?

**Comment by FredKSchott** [comment] 2021-07-29 22:09
Just triple checking: is this still happening on latest Astro version? We just dramatically improved this in the v0.18.0 release that went out on Tuesday.

**Comment by wiesson** [comment] 2021-07-30 06:34
I will check it later to today!

**Comment by amatiasq** [comment] 2021-07-30 10:22
I'm unable to reproduce this in 0.18

**Comment by FredKSchott** [comment] 2021-07-30 17:30
Great! Thanks for confirming

**Closed by FredKSchott** 2021-07-30 17:30 UTC
