### ISSUE TITLE
🐛 BUG: `astro build` produces unpredictable CSS order when using both `style` and `link` tags 

### ISSUE THREAD

**Issue by austincrim** [snowpackjs/astro#647] opened 2021-07-09 15:19 UTC
### What package manager are you using?

yarn

### What operating system are you using?

Mac OS Catalina

### Describe the Bug

If a given Astro component has both a `style` tag and `link`ed CSS files, the resulting build will produce varying results depending on whether the `style` tag is in a `head` tag or not. If the `style` tag is not in the same `head` as the `link`, the CSS brought in with the `link` will actually override the CSS in the component's `style` tag.

@drwpow pointed to [this code](https://github.com/snowpackjs/astro/blob/main/packages/astro/src/build.ts#L285) as a possible culprit.

### Steps to Reproduce

1. `npm init astro` using template starter
2. add `style` tag to `index.astro` outside of the `head`
3. run `astro build` and view resulting CSS
4. move `style` tag inside `head` and rerun `astro build`

### Link to Minimal Reproducible Example (Optional)

https://github.com/austincrim/repro-astro-build-css-order

**Comment by matsdahlin** [comment] 2021-08-04 22:49
I can't reproduce this in the the current main branch, is this resolved?

**Comment by natemoo-re** [comment] 2021-11-02 22:18
I'm going to close this since all the offending code has likely been rewritten in our migration from Snowpack to Vite!

If this remains an issue in `astro >= 0.21.0` please open a new ticket!

**Closed by natemoo-re** 2021-11-02 22:18 UTC
Labels: good first issue
