### ISSUE TITLE
💡 RFC: "ignore blocks" inside .astro files

### ISSUE THREAD

**Issue by jeffjose** [snowpackjs/astro#974] opened 2021-08-01 17:14 UTC
### Background & Motivation

There should an easy way to have "ignore blocks" inside astro files. The most obvious case is for php blocks, such as the one described below

```html
// index.astro
<h1>Hello World!</h1>
<?php
 echo "Hello from php!"
?>
```

*Expected output*
```html
// index.html (expected)
<html>
<head>..</head>
<body>
<h1>Hello World!</h1>
<?php
 echo "Hello from php"
?>
</body>
</html>
```

### Possible solutions
*A tag *
```html
// index.astro

<escape>
<?php
echo "Hello"
?>
</escape>
```
 Another possibility is a block indicator
```html
// index.astro
<h1> Hello World! </h1>
---
<?php
echo "Hello World!"
?>
---
```

### Help make it happen!

- [ ] I am willing to submit a PR to implement this change.
- [ ] I am willing to submit a PR to implement this change, but would need some guidance.
- [X] I am not willing to submit a PR to implement this change.

**Comment by matthewp** [comment] 2021-08-02 13:12
Thanks @jeffjose, are you expecting the php bits to be rendered as strings? So the user will see the tags? If so I think you can achieve this today using html entities:

```
&lt;?php
echo "Hello"
?&gt;
```

**Comment by jasikpark** [comment] 2021-08-02 14:12
How permissive is Astro meant to be with syntax? Is it as permissive as HTML or is it more like JSX?

**Comment by jeffjose** [comment] 2021-08-02 14:58
Didnt know about html entities, but I was thinking more about a generalized escaping solution. 

Similar to php, which does further processing on astro output, in the future people could compose pipelines that starts with astro and its output going through other parsers.

**Comment by matthewp** [comment] 2021-08-02 16:26
@jasikpark like HTML

**Comment by jeffjose** [comment] 2021-08-02 16:50
To the question on the expect output format - yes, they should be strings.

**Comment by jeffjose** [comment] 2021-08-11 23:25
Gentle ping :)

**Comment by drwpow** [comment] 2021-08-17 16:05
I’d recommend accomplishing this like so:

```
---
import { encode } from 'html-entities';
---
<code><pre>
  {encode(`<?php
echo "Hello World"
?>
  `)}
</code></pre>
```

I think I’m generally -1 in favor of a tag that does this, because it disrupts HTML’s parser and now you’re in a different context where different rules apply (and with that comes unexpected behavior and possible bugs). Like @matthewp suggested, HTML entities are the established way to solve this problem, and there are already many existing utilities like [html-entities](https://www.npmjs.com/package/html-entities) that make them easy to work with.

**Comment by FredKSchott** [comment] 2021-08-31 17:05
Yup, this is a pattern in React, Svelte, etc. that we follow.

**Comment by matthewp** [comment] 2021-09-27 19:19
As this proposal has two -1s from core team members and no current champion I'm going to close the issue. We can reopen when someone is willing to champion a proposal on solving this problem.

**Closed by matthewp** 2021-09-27 19:19 UTC

**Comment by jasikpark** [comment] 2021-09-28 00:48
I might have a similar idea to cook up soon...
