### ISSUE TITLE
🐛 BUG: Build fails with empty JS files

### ISSUE THREAD

**Issue by itday** [snowpackjs/astro#1122] opened 2021-08-16 00:14 UTC
### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

The build process fails if an empty JS file is included.

### Steps to Reproduce

1. `npm init astro`
2. `npm install`
3. Add `<script src="/script.js"/>` to an astra file
3. Add an *empty* JS file in the public folder
4. Build fails with: could not find "script.js"

**Comment by MarcusOtter** [comment] 2021-08-16 00:24
This looks similar to https://github.com/snowpackjs/astro/issues/1046

**Comment by jasikpark** [comment] 2021-08-16 02:35
a simpler answer is that you can add `let x = 2;` and also get Astro to be happy with it. I would say for this specific case it makes the most sense to warn that the file is empty and successfully build with a link to the file. 

I'm not sure it's the same as # since it's not accessing exports, it's just a simple script tag.

**Comment by matthewp** [comment] 2021-08-24 20:50
This is likely fixed by https://github.com/snowpackjs/astro/pull/1196

**Comment by FredKSchott** [comment] 2021-11-19 18:45
Thanks for the report! We believe that this has been fixed in astro v0.21, going out today. Let us know if you can still reproduce the issue after updating to v0.21 and we'll be happy to take a look.

**Closed by FredKSchott** 2021-11-19 18:45 UTC
Labels: good first issue
