### ISSUE TITLE
🐛 BUG: panic: html: bad parser state: originalIM was set twice

### ISSUE THREAD

**Issue by CM-IV** [snowpackjs/astro#1953] opened 2021-11-20 20:34 UTC
### What version of `astro` are you using?

0.21.0

### What package manager are you using?

npm

### What operating system are you using?

Ubuntu Linux

### Describe the Bug

Experienced an issue with what seems like the Golang html parser in net/html/parse.go.

This error occurs upon navigating to the "contact" page that has a Netlify form in it.

**panic: html: bad parser state: originalIM was set twice**

I could not get stackblitz or codesandbox to show changes to the files when editing them on both Chromium and Firefox, so the stackblitz URL will not help you.

**I kindly ask that you clone the dev branch of this repo here:**

```
git clone -b dev git@github.com:CM-IV/Astro-website.git
```
Here is a link to the relevant Golang [code](https://github.com/golang/net/blob/master/html/parse.go).

Prior to migrating to 0.21.0, everything was working perfectly on 0.20, as the master branch is deployed.

There are no frontend JavaScript frameworks actually used in this project, there are only .astro files.

![Screenshot from 2021-11-20 14-13-30](https://user-images.githubusercontent.com/44551614/142739914-433d6cac-a6ea-4f22-9351-334e2d0bc595.png)
![Screenshot from 2021-11-20 14-14-20](https://user-images.githubusercontent.com/44551614/142739916-d99d47ee-eab6-46ac-bbb0-7102a9b6b160.png)

Error seems to go away after the Netlify html form is commented out:

![Screenshot from 2021-11-20 14-54-47](https://user-images.githubusercontent.com/44551614/142740660-c5deda2a-1339-4915-bac1-4f5650ebc4a5.png)

## Update

I have narrowed the problem down to this commented out textarea.  When the textarea is commented out, the content page returns a 200 status as it should.

![Screenshot from 2021-11-20 14-55-03](https://user-images.githubusercontent.com/44551614/142740666-e7e08d57-8cd8-4d8d-8c8c-c4361d492b50.png)

![Screenshot from 2021-11-20 15-13-57](https://user-images.githubusercontent.com/44551614/142741175-4762d950-d909-4c1d-b92a-e7d541cb19d9.png)

### Link to Minimal Reproducible Example

https://github.com/CM-IV/Astro-website/tree/dev

**Comment by natemoo-re** [comment] 2021-11-20 22:45
Thanks for narrowing this down! We'll take a look!

**Comment by natemoo-re** [comment] 2021-11-20 23:32
OK I can confirm that this an issue in the parser! We're working on a fix.

As a temporary workaround, it looks like removing the parent `html` element above `<Wrapper>` fixes this. The `Wrapper.astro` file already has an `html` element.

**Comment by natemoo-re** [comment] 2021-11-21 02:25
Alright, made a fix on https://github.com/snowpackjs/astro-compiler/pull/159! Hope to get it reviewed and merged in as soon as we can. Will definitely be out in the next patch.

**Closed** 2021-11-22 17:39 UTC
