### ISSUE TITLE
🐛 BUG: node imports broke in 0.21

### ISSUE THREAD

**Issue by innermatrix** [snowpackjs/astro#1852] opened 2021-11-17 06:10 UTC
### What version of `astro` are you using?

0.21.0-next.5

### What package manager are you using?

npm

### What operating system are you using?

macOS

### Describe the Bug

In 0.20.12 I was able to import `node:foo`; in 0.21, I get an error. Indirect imports of `node:foo` also don't work. For example, this breaks `build`: 

```ts
import { globby } from "globby";
```

Worked fine in 0.20.12 (you can verify by changing the Astro version in `package.json` of the supplied MRE)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-t3hheb-cnlewa

**Comment by jakobpevec** [comment] 2021-11-17 08:02
I had a similar issue. In 0.20.12 I could import these packages like so:
```
import gsap from "gsap/gsap";
import ScrollTrigger from "gsap/ScrollTrigger";
```

Changing the paths like in the example below resolved the import errors. I'm still struggling with getting things to work due to styles getting 404 errors.
```
import gsap from "gsap/dist/gsap";
import ScrollTrigger from "gsap/dist/ScrollTrigger";
```

**Comment by jonathantneal** [comment] 2021-11-17 13:54
Thanks for reporting this, @innermatrix.

I’ve verified your reproduction @ https://stackblitz.com/edit/github-t3hheb-cnlewa?file=src/pages/index.astro

**Comment by natemoo-re** [comment] 2021-11-17 16:36
There is a PR in progress to fix this! https://github.com/snowpackjs/astro/pull/1771

**Comment by FredKSchott** [comment] 2021-11-18 07:20
The fix for this went out in the latest `next` release!

**Closed by FredKSchott** 2021-11-18 07:20 UTC

**Comment by innermatrix** [comment] 2021-11-20 05:49
@FredKSchott I am unable to verify this because my MWE is still failing in `0.21.0-next.12` albeit with a different error (`ReferenceError: require is not defined`). Please have a look at the MWE pinned to `next.12` at https://stackblitz.com/edit/github-t3hheb-3oxyah?file=package.json and lmk whether this should be filed as a separate issue.
