### ISSUE TITLE
🐛 BUG: Prism styles doesn't get added if code is present in Markdown component's content

### ISSUE THREAD

**Issue by ghoshnirmalya** [snowpackjs/astro#836] opened 2021-07-23 18:08 UTC
### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

I'm using the [Markdown component](https://docs.astro.build/reference/builtin-components#markdown-) like this:
```ts
<Markdown content={article.body_markdown} />
```

If `article.body_markdown` has code inside it, the Prism styles don't get injected. Instead **astro-uKNRpSHA** gets added as the class name:

<img width="552" alt="Screenshot 2021-07-23 at 11 24 22 PM" src="https://user-images.githubusercontent.com/6391763/126822658-1d7c07bf-cd26-4145-906c-09ecea91a667.png">

The issue can be viewed [on this page](https://astro-docs-example.vercel.app/articles/integrating-tailwindcss-with-next-js-2kl3). I'm unsure if the Prism classes will be added automatically like how it does in the [documentation site](https://docs.astro.build/core-concepts/collections):

<img width="356" alt="Screenshot 2021-07-23 at 11 33 10 PM" src="https://user-images.githubusercontent.com/6391763/126822959-cb71532c-1e7a-46e0-88a4-e9e13fc35590.png">

### Steps to Reproduce

1. Visit https://astro-docs-example.vercel.app/articles/integrating-tailwindcss-with-next-js-2kl3.
2. Click on inspect element.
3. Inspect on any code snippet.

### Link to Minimal Reproducible Example (Optional)

https://github.com/ghoshnirmalya/astro-docs-example

**Comment by matthewp** [comment] 2021-07-29 18:58
Dupe of #699, closing but thanks or bringing this up again, we intend to fix soon.

**Closed by matthewp** 2021-07-29 18:58 UTC
Labels: markdown
