### ISSUE TITLE
Using inline functions to render HTML can cause Astro take a long time to fail

### ISSUE THREAD

**Issue by ewatch** [snowpackjs/astro#348] opened 2021-06-09 09:25 UTC
When using an inline function like this the astro dev server keeps the connection to the browser open, because there is no wrapper DOM element in the inline function. Removing the `<br />` at the end makes it work again.

````
---
import ships from '../data/ships.json';
---
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Ships</title>
  </head>
  <body>  
    {ships.map((ship) => {
      return (<div><a href="#">{ship.name}</a></div><br />)
    })}
    abcderf
  </body>
</html>
````

**Comment by FredKSchott** [comment] 2021-06-15 00:07
Closing as a duplicate of #405, which @natemoo-re has a fix out for already via #433.

@natemoo-re correct me if I'm wrong, and this isn't fixed by that PR.

**Closed by FredKSchott** 2021-06-15 00:07 UTC
Labels: bug
