### ISSUE TITLE
css @import with relative path not working as expected

### ISSUE THREAD

**Issue by npup** [snowpackjs/astro#308] opened 2021-06-06 23:05 UTC
When a referenced css file has imports, the imported files are not found in a "built" project - the paths seems to be wrong.
The imports are only working as expected when running the dev server.

```
// ./public/style/main.css - included from template.astro with <link rel="stylesheet" href="/style/main.css">
@import "./extra.css";

body {
  /* something */
};
```
```
// ./public/style/extra.css
p {
  /* something */
}
```

In the built version of `main.css`, the import path is not fit to find the `extra.css` file anymore.

Reproduction and description repo: https://github.com/npup/astro-issue-css-imports-minimal-repro

**Comment by FredKSchott** [comment] 2021-06-17 16:14
https://github.com/snowpackjs/astro/issues/480 was just filed using our new issue template, so I'm going to close this one in favor of that one. Thanks for filing! and please feel free to join in #480

**Comment by FredKSchott** [comment] 2021-06-21 05:49
Actually, this is a duplicate of https://github.com/snowpackjs/astro/issues/454

**Closed by FredKSchott** 2021-06-21 05:49 UTC
