### ISSUE TITLE
🐛 BUG: Unable to use Destructuring Syntax for Component Props

### ISSUE THREAD

**Issue by L1lith** [snowpackjs/astro#660] opened 2021-07-12 06:33 UTC
### What package manager are you using?

I believe NPM, though I do have pnpm installed globally it's not configured to use it

### What operating system are you using?

Windows 10, Node v14.15.5, Astro@0.17.0

### Describe the Bug

Here's the error log, I'm not sure why this is happening
```
TypeError: Cannot read property 'startsWith' of undefined
 at file:///C:/Users/USERNAME/Projects/PROJECTNAME/client/node_modules/astro/src/compiler/transform/head.ts:28:81
    at Array.some (<anonymous>)
    at Object.enter (file:///C:/Users/USERNAME/Projects/PROJECTNAME/client/node_modules/astro/src/compiler/transform/head.ts:28:52)
    at Object.enter (file:///C:/Users/USERNAME/Projects/PROJECTNAME/client/node_modules/astro/src/compiler/transform/index.ts:62:14)
    at SyncWalker.visit (file:///C:/Users/USERNAME/Projects/PROJECTNAME/client/node_modules/estree-walker/src/sync.js:49:16)
    at SyncWalker.visit (file:///C:/Users/USERNAME/Projects/PROJECTNAME/client/node_modules/estree-walker/src/sync.js:79:18)
    at SyncWalker.visit (file:///C:/Users/USERNAME/Projects/PROJECTNAME/client/node_modules/estree-walker/src/sync.js:79:18)
    at walk (file:///C:/Users/USERNAME/Projects/PROJECTNAME/client/node_modules/estree-walker/src/index.js:20:18)
    at walkAstWithVisitors (file:///C:/Users/USERNAME/Projects/PROJECTNAME/client/node_modules/astro/src/compiler/transform/index.ts:57:3)
    at transform (file:///C:/Users/USERNAME/Projects/PROJECTNAME/client/node_modules/astro/src/compiler/transform/index.ts:95:3)
    at convertAstroToJsx (file:///C:/Users/USERNAME/Projects/PROJECTNAME/client/node_modules/astro/src/compiler/index.ts:36:9)
    at transformFromSource (file:///C:/Users/USERNAME/Projects/PROJECTNAME/client/node_modules/astro/src/compiler/index.ts:91:20)
    at compileComponent (file:///C:/Users/USERNAME/Projects/PROJECTNAME/client/node_modules/astro/src/compiler/index.ts:110:24)
    at Object.load (C:\Users\USERNAME\Projects\PROJECTNAME\client\node_modules\astro\snowpack-plugin.cjs:68:28)
    at runPipelineLoadStep (C:\Users\USERNAME\Projects\PROJECTNAME\client\node_modules\snowpack\lib\index.js:123895:32)
    at Object.buildFile (C:\Users\USERNAME\Projects\PROJECTNAME\client\node_modules\snowpack\lib\index.js:124095:24)
    at C:\Users\USERNAME\Projects\PROJECTNAME\client\node_modules\snowpack\lib\index.js:157676:37
    at FileBuilder.build (C:\Users\USERNAME\Projects\PROJECTNAME\client\node_modules\snowpack\lib\index.js:157688:32)
    at Object.loadUrl (C:\Users\USERNAME\Projects\PROJECTNAME\client\node_modules\snowpack\lib\index.js:177102:17)
    at load (C:\Users\USERNAME\Projects\PROJECTNAME\client\node_modules\snowpack\lib\index.js:176699:28)
    at C:\Users\USERNAME\Projects\PROJECTNAME\client\node_modules\snowpack\lib\index.js:169273:32
    at async Promise.all (index 1) {
  __snowpackBuildDetails: { name: 'snowpack-astro', step: 'load' }
```

### Steps to Reproduce

pages/index.astro
```
---
import StandardLayout from '../components/StandardLayout.astro'
---
<StandardLayout head={{title: "Inspection Tracker"}}>
  <table>
  </table>
</StandardLayout>
```

components/Head.astro
```
---
const title = Astro.props.hasOwnProperty('title') ? Astro.props.title + " - Site name" : "Site name"
---
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{title}</title>
    <link rel="icon" type="image/svg+xml" href="/favicon.svg">
    <link rel="stylesheet" href="/style/global.css">
    <link rel="stylesheet" href="/style/home.css">
    <slot/>
</head>
```

components/StandardLayout.astro
```
---
// Component Imports
import Head from '../components/Head.astro';

const headOptions = typeof Astro.props.head == 'object' && Astro.props.head !== null ? Astro.props.head : {}
---
<html lang="en">
<Head {...headOptions}/>
<body>
    <main id="page">
        <slot/>
    </main>
</body>
</html>
```

**Comment by akellbl4** [comment] 2021-07-12 10:08
I though it is connected with `map` in my case #653

**Comment by natemoo-re** [comment] 2021-07-12 16:57
Thanks for opening an issue, I think I might know what's going on here. I'll take a look. 👍🏻 

---

As an aside, I don't think you can avoid `hasOwnProperty` and simplify some of the prop checks here.

components/Head.astro
```js
const SITE_NAME = "Site Name";
const { title } = Astro.props;
const title = title ? `${title} - ${SITE_NAME}` : SITE_NAME; 
```

components/StandardLayout.astro
```js
// Component Imports
import Head from '../components/Head.astro';

const { head: headOptions = {} } = Astro.props;
```

**Comment by akellbl4** [comment] 2021-07-12 20:26
@natemoo-re I've closed my issue and PR because I think this issue is more relevant and PR isn't really useful.

**Comment by natemoo-re** [comment] 2021-07-12 20:29
@akellbl4 Great, thanks! Will keep you all in the loop on this one.

**Comment by FredKSchott** [comment] 2021-07-20 21:37
@natemoo-re assigning you since it sounds like you've done some work here

**Comment by jasikpark** [comment] 2021-08-30 06:09
was this fixed by #832?

**Comment by jasikpark** [comment] 2021-09-08 23:28
I've made a reproduction of the original source code at https://codesandbox.io/s/astro-660-reproduction-ih735?file=/src/components/StandardLayout.astro. I got the error: `[parse-error] [64:318]: Expected ')'` 

I don't see any incorrect syntax.. it seems just like an unsupported syntax for the parser.

I'll mark it `compiler-v2` for now to be revisited with the rewrite!

**Comment by natemoo-re** [comment] 2021-09-22 18:11
Confirmed that this is working in the new compiler! [See REPL link](https://astro.build/play#eyJpbm1lbW9yeTovL21vZGVsL3NyYy9wYWdlcy9QYWdlLmFzdHJvIjoiLS0tXG4vLyBDb21wb25lbnQgSW1wb3J0c1xuaW1wb3J0IEhlYWQgZnJvbSAnLi4vY29tcG9uZW50cy9Db21wb25lbnQuYXN0cm8nO1xuXG5jb25zdCBoZWFkT3B0aW9ucyA9IHR5cGVvZiBBc3Ryby5wcm9wcy5oZWFkID09ICdvYmplY3QnICYmIEFzdHJvLnByb3BzLmhlYWQgIT09IG51bGwgPyBBc3Ryby5wcm9wcy5oZWFkIDoge307XG4tLS1cbjxodG1sIGxhbmc9XCJlblwiPlxuPEhlYWQgey4uLmhlYWRPcHRpb25zfSAvPlxuPGJvZHk+XG4gICAgPG1haW4gaWQ9XCJwYWdlXCI+XG4gICAgICAgIDxoMT5IZWxsbyB3b3JsZCE8L2gxPlxuICAgICAgICA8c2xvdC8+XG4gICAgPC9tYWluPlxuPC9ib2R5PlxuPC9odG1sPlxuIiwiaW5tZW1vcnk6Ly9tb2RlbC9zcmMvY29tcG9uZW50cy9Db21wb25lbnQuYXN0cm8iOiItLS1cbmNvbnN0IHRpdGxlID0gQXN0cm8ucHJvcHMuaGFzT3duUHJvcGVydHkoJ3RpdGxlJykgPyAoQXN0cm8ucHJvcHMudGl0bGUgKyBcIiAtIFNpdGUgbmFtZVwiKSA6IFwiU2l0ZSBuYW1lXCI7XG4tLS1cbjxoZWFkPlxuICAgIDxtZXRhIGNoYXJzZXQ9XCJVVEYtOFwiPlxuICAgIDxtZXRhIG5hbWU9XCJ2aWV3cG9ydFwiIGNvbnRlbnQ9XCJ3aWR0aD1kZXZpY2Utd2lkdGgsIGluaXRpYWwtc2NhbGU9MVwiPlxuICAgIDx0aXRsZT57dGl0bGV9PC90aXRsZT5cbiAgICA8bGluayByZWw9XCJpY29uXCIgdHlwZT1cImltYWdlL3N2Zyt4bWxcIiBocmVmPVwiL2Zhdmljb24uc3ZnXCI+XG4gICAgPGxpbmsgcmVsPVwic3R5bGVzaGVldFwiIGhyZWY9XCIvc3R5bGUvZ2xvYmFsLmNzc1wiPlxuICAgIDxsaW5rIHJlbD1cInN0eWxlc2hlZXRcIiBocmVmPVwiL3N0eWxlL2hvbWUuY3NzXCI+XG4gICAgPHNsb3QgLz5cbjwvaGVhZD5cbiJ9).

**Closed by natemoo-re** 2021-09-22 18:11 UTC
Labels: compiler-v2
