### ISSUE TITLE
🐛 BUG: Open bracket not show correctly in markdown code block

### ISSUE THREAD

**Issue by bramaudi** [snowpackjs/astro#1018] opened 2021-08-05 13:39 UTC
### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

Intead showing { the bracket symbol will show as raw html entities `&#123;` in markdown code block.

### Steps to Reproduce

Write normal css using markdown code block

```
```css
```

Perhaps this bug is not complete fix of #233 issue?

**EDIT:** Add temporarily solution to get the job done

Currently i'm just using simple javscript code to fix that by replace all incorrect open bracket in rendered code block.

```js
for (const code of document.querySelectorAll('code')) {		
	code.innerHTML = code.innerHTML.replace(/&amp;#123;/g, '{')
}
```

**Comment by mmarkelov** [comment] 2021-08-07 17:08
duplicate of #727

**Closed** 2021-08-07 17:21 UTC
