### ISSUE TITLE
🐛 BUG: astro breaks with Swiper

### ISSUE THREAD

**Issue by radiosilence** [snowpackjs/astro#909] opened 2021-07-28 15:06 UTC
### What package manager are you using?

yarn

### What operating system are you using?

MacOS

### Describe the Bug

[Swiper](https://github.com/nolimits4web/swiper) is a popular swipe carousel library.

When adding it to a project and trying to use it inside a component, we get the following error on dev or build:

```
TypeError: Cannot read property 'fn' of undefined
    at file:///xxx/my-astro-project/src/pages/index.astro
    at eval (/_snowpack/pkg/swiper.core.v6.8.0.js:55:32)
    at Array.forEach (<anonymous>)
    at eval (/_snowpack/pkg/swiper.core.v6.8.0.js:54:22)
    at Object.createCommonjsModule (/_snowpack/pkg/swiper.v6.8.0/common/_commonjsHelpers-a2fb9dda.js:14:5)
    at eval (/_snowpack/pkg/swiper.core.v6.8.0.js:9:21)
    at initializeModule (/xxx/my-astro-project/node_modules/snowpack/lib/index.js:169283:13)
    at /xxx/my-astro-project/node_modules/snowpack/lib/index.js:169273:32
    at async Promise.all (index 1)
    at initializeModule (/xxx/my-astro-project/node_modules/snowpack/lib/index.js:169272:17)
    at /xxx/my-astro-project/node_modules/snowpack/lib/index.js:169273:32
    at async Promise.all (index 1)
    at initializeModule (/xxx/my-astro-project/node_modules/snowpack/lib/index.js:169272:17)
    at load (file:///xxx/my-astro-project/node_modules/astro/src/runtime.ts:106:17)
    at buildStaticPage (file:///xxx/my-astro-project/node_modules/astro/src/build/page.ts:95:18)
    at async Promise.all (index 0)
    at build (file:///xxx/my-astro-project/node_modules/astro/src/build.ts:77:7)
    at buildAndExit (file:///xxx/my-astro-project/node_modules/astro/src/cli.ts:16:15)
```

It seems to be using the commonjs files. We can see by swiper's project/build layout that it outputs both .cjs.js and .esm.js entry points, so perhaps astro/snowpack just needs to use `module` entry rather than `main` entry. 

### Steps to Reproduce

See project below

### Link to Minimal Reproducible Example (Optional)

https://github.com/radiosilence/astro-bug-909

**Comment by radiosilence** [comment] 2021-08-05 15:24
If I create a patch for that commonjs file, so it doesn't try and do a stupid thing, I now get this error when we try to mount Swiper:

```
Uncaught (in promise) Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
```

**Comment by drwpow** [comment] 2021-08-19 16:44
You’re right that normally Snowpack does use the `module` entrypoint for packages. But we’re using Snowpack in SSR mode, which runs in a Node/CommonJS environment. And in SSR mode, we do prefer CommonJS over ESM for now because that’s just what most of the ecosystem is still using, unfortunately. Also, it’s really hard to just prefer `module`, because some packages use that to point to Node ESM code, while others use that to point to browser ESM, which are 2 totally different things. We try and just strike a balance of what works for _most_ packages, but it’s hard to get it right for everything.

You can get around the first issue by requiring `import … from 'swiper/swiper.esm';` directly, which gets around the CommonJS issue.

Also worth pointing out: you need to `export default Carousel` in `Carousel.tsx` to not see that “undefined component” error.

But your `Error: Invalid hook call. Hooks can only be called inside of the body of a function component.` error is a bit trickier! That happens because of React’s check that prevents 2 copies of React running. And swiper is accidentally loading its own copy of `react` separately from your project. This is actually an easy error to get with React, unfortunately.

I think this is a real bug, but it lies within esinstall, not Astro, technically. I’ve opened up an issue here to track it: https://github.com/snowpackjs/snowpack/issues/3667.

Fortunately, though, I think some upcoming changes will fix this issue! So rather than close this issue I’ll leave it open in light of that.

**Comment by radiosilence** [comment] 2021-08-25 14:05
@drwpow thank you so much for your detailed response!

**Comment by radiosilence** [comment] 2021-09-09 12:58
@Can2Nya 
```
[executing astro] TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at extend (/_snowpack/pkg/swiper.react.v6.8.2.js:8827:10)
    at getParams (/_snowpack/pkg/swiper.react.v6.8.2.js:8915:20)
    at Object.eval [as render] (/_snowpack/pkg/swiper.react.v6.8.2.js:9473:46)
    at ReactDOMServerRenderer.render (/_snowpack/pkg/react-dom.server.v17.0.2.js:3849:44)
    at ReactDOMServerRenderer.read (/_snowpack/pkg/react-dom.server.v17.0.2.js:3675:29)
    at Object.renderToString (/_snowpack/pkg/react-dom.server.v17.0.2.js:4275:27)
    at Object.renderToStaticMarkup (/_snowpack/pkg/@astrojs.renderer-react.server.v0.2.0.js:43:22)
    at __astro_component_internal (/_snowpack/pkg/astro.dist.internal.__astro_component.v0.20.4.js:199:48)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async Object.h (/_snowpack/pkg/astro.dist.internal.h.v0.20.4.js:45:20)
    at async Promise.all (index 1)
    at async Object.h (/_snowpack/pkg/astro.dist.internal.h.v0.20.4.js:45:20)
    at async Promise.all (index 2)
```

Not sure what's going on here.

**Comment by FredKSchott** [comment] 2021-11-19 18:01
Thanks for the report! We believe that this has been fixed in astro v0.21, going out today. Let us know if you can still reproduce the issue after updating to v0.21 and we'll be happy to take a look.

**Closed by FredKSchott** 2021-11-19 18:01 UTC
Labels: 0.21

**Comment by natemoo-re** [comment] 2021-11-19 18:04
There might be a similar issue in v0.21, which we are tracking on https://github.com/snowpackjs/astro/issues/1878. Please continue the discussion there.

**Comment by tpiros** [comment] 2021-12-30 14:54
I'm having a similar issue but with Slick (https://react-slick.neostack.com). I'm on `v0.21.13`.
