### ISSUE TITLE
🐛 BUG: No syntax highlighting in Markdown component when `content` prop is used

### ISSUE THREAD

**Issue by benborgers** [snowpackjs/astro#850] opened 2021-07-25 19:07 UTC
### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Code blocks in markdown are properly tokenized for syntax highlighting when they're written directly into the file inside the `<Markdown>` component: 

```
<Markdown>
  ```js
  const foo = 'bar'
  \```
</Markdown>
```

_(I inserted the `\` so GitHub's rendering would work)_ 

But the tokenization does not happen when the `content` prop of the Markdown component is used: 

```
<Markdown content={markdownString} />
```

### Steps to Reproduce

1. Create a new Astro project with Starter Kit starter. 
2. Import the `Markdown` component from `astro/components` in the `index.astro` file. 
3. Write markdown with a code block in the two ways described above (directly into the component; as a string passed into the `content` prop). 
4. Start the Astro dev server and inspect element. The code block within `<pre></pre>` will be tokenized with Prism when written directly as a child of the component, but won't be tokenized when passed as a string into the `content` prop. 

### Link to Minimal Reproducible Example (Optional)

https://github.com/benborgers/astro-issue-syntax-highlighting

**Comment by matthewp** [comment] 2021-07-26 16:23
Thanks! The cause here is because Prism syntax highlighting happens in the Astro compiler. Dynamic markdown content only gets compiled through our markdown support. 

The fix is probably to move the syntax highlighting part to inside of the Markdown code.

**Comment by madx** [comment] 2021-07-29 05:06
Possible duplicates: 
https://github.com/snowpackjs/astro/issues/699
https://github.com/snowpackjs/astro/issues/850

**Comment by matthewp** [comment] 2021-07-29 18:58
Dupe of #699, closing but thanks or bringing this up again, we intend to fix soon.

**Closed by matthewp** 2021-07-29 18:58 UTC
Labels: markdown
