### ISSUE TITLE
💡 RFC: Add an SPA component to the built-in components

### ISSUE THREAD

**Issue by RafidMuhymin** [snowpackjs/astro#1216] opened 2021-08-24 16:09 UTC
### Background & Motivation

The Six UI frameworks supported by Astro for templating are primarily used for building SPA. But the application generated by Astro isn't an SPA. And, it's also not possible because Astro turns the component into plain HTML and ships zero JS!

But to enjoy the advantages of an SPA, I have written a tiny script for my personal project that can turn an Astro website into an SPA. It's not only just an SPA component/library but it comes with many other features also.

The complete list of features:

1. It prefetches the internal links using Intersection Observer for blazing-fast navigation
2. It upgrades from prefetch to fetch on mouseover and touchstart if the resource hasn't been prefetched already
3. It caches the prefetched resources using the Cache API
4. It intercepts when you click on an internal link and then it tries to serve the request from cache, if a cache isn't found, it fetches the requested page and replace the current documentElement with the new documentElement
5. Then it executes the scripts of the navigated page
6. It shows a fade-in animation when the new page loads
7. It dispatches a prefetch function and navigate function that can be used for prefetching and navigating programmatically
8. It has two lifecycle functions, onNavigate & onMount that can be called to add effects and execute code
9. It also works with popstate events (back/forward navigation)
10. It clears the entire cache on page load/reloads to ensure there's no stale content
11. If data saver is enabled (on mobile devices), it won't fetch or prefetch the pages

### Installing the plugin (Until it gets accepted and added to the core)

Once you setup your Astro project simply run the following command:

```bash
# yarn
yarn add astro-spa

#npm
npm i astro-spa
```

You can then import the component like this:

```astro
---
import { Spa } from 'astro-spa'
// or import Spa from 'astro-spa/Spa.astro'
---
<Spa/>
```

And that's it, you're now ready to go!

### Demos

[https://astro-spafy-component-demo.netlify.app/]
[https://ohka-bots-site-astro-ksoqn4flk7-j2q7uvclm-tc-001.vercel.app/] (Thanks to @Tc-001)

### Source Code
You can also view the source script file at this URL:
https://github.com/RafidMuhymin/travel-guru-astro-preact/blob/main/public/spafy.js

### Help make it happen!

- [X] I am willing to submit a PR to implement this change.
- [ ] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by okikio** [comment] 2021-08-24 21:31
I'd suggest creating a separate SPA library just for Astro, or waiting till the [appHistory api](https://github.com/WICG/app-history) is complete. appHistory is a means of fixing all the bugs and issues involved with creating an SPA with the current `window.history.pushState/replaceState`.

**Comment by RafidMuhymin** [comment] 2021-08-25 06:23
@okikio The demo spa component already tries to fix all the issues related with pushState. And it's also not only just a spa component, it also utilizes prefetching & fetching techniques combined with the Cache API to give a blazing-fast experience. And I think the appHistory API should be adopted when it'll be available. Because waiting years just for a good API isn't a good idea at all.

**Comment by okikio** [comment] 2021-08-25 07:27
> I think the appHistory API should be adopted when it'll be available. Because waiting years just for a good API isn't a good idea at all.

I understand your enthusiasm, I've also created PJAX library before (https://github.com/okikio/native), the problem is that there are too many pit falls and bugs involved. 

My main complaint is that I don't think this should be built into Astro. 
1. Astro tries to ship 0 js by default. Let's stick to this for as long we can
2. AppHistory will ensure a great SPA user experience so I thinks we should encourage that; its better to wait a couple years to ship a higher quality product than to rush to get the product out with  more bugs.
3. This proposal would be very similar to react-router or other SPA Frameworks, thus (at least in my mind) it should be a separate package not built into Astro

**Comment by jasikpark** [comment] 2021-08-27 23:08
Why don't you publish this component on npm today, while this rfc is still being discussed so people can use it today! I have similar reservations of pulling this into core, but I'd love to see something like this with a great developer experience available in the community! https://docs.astro.build/guides/publish-to-npm -- there's a list of astro packages on this page that we probably need to update :D

**Comment by RafidMuhymin** [comment] 2021-08-28 11:36
Great suggestion @jasikpark! I'll work on publishing the component to npm this week.

**Comment by RafidMuhymin** [comment] 2021-08-28 12:23
Just published the component to npm! Run `yarn add astro-spa` or `npm i astro-spa` to install the package, and then `import spa from "astro-spa"`.

**Comment by matthewp** [comment] 2021-09-27 18:59
@RafidMuhymin This would be a great thing to show off at a future Demo day if you'd be interested some time.

**Comment by jasikpark** [comment] 2021-10-05 17:53
`astro-seo` is now featured on <https://docs.astro.build/themes#featured-packages>! I'm going to close this for now, but we can reopen if there's a new attempt to make this part of core, rather than a solid community contribution!

lmk if I should reopen!

**Closed by jasikpark** 2021-10-05 17:53 UTC

**Comment by RafidMuhymin** [comment] 2021-10-09 10:40
@jasikpark Though `astro-spa` is now a featured package I still think this should be a core thing or an official package (this term wasn't available at the time I posted this RFC). Because the UI libraries that Astro currently supports for templating and adding reactivity, all are used primarily to build SPA.

**Comment by RafidMuhymin** [comment] 2021-10-09 10:40
@matthewp I'm interested in doing a demo video!

**Comment by okikio** [comment] 2021-10-09 16:53
In my mind it shouldn't be a built in package, as it adds js to your page. IMO, it should be a separate package.

**Comment by RafidMuhymin** [comment] 2021-10-10 10:16
@okikio I agree with you. I was talking about official package not built-in in the previous comment

**Comment by okikio** [comment] 2021-10-10 16:06
Wait I thought it was already official
