### ISSUE TITLE
🐛 BUG: Aliases and Partial Hydration, problem generating client-side JavaScript

### ISSUE THREAD

**Issue by ra-devweb** [snowpackjs/astro#1223] opened 2021-08-25 01:50 UTC
### What package manager are you using?

yarn

### What operating system are you using?

Linux

### Describe the Bug

When I create first the project I started by adding the aliases because it's a handy shortcut for imports, so everything was working well till I want to use Partial Hydration to handle the navigation mobile toggling, then it's starting to giving me this error below   
![Image of error](https://i.ibb.co/ykKrx9x/Screenshot-from-2021-08-25-01-40-18.png)
![Image of erro](https://i.ibb.co/PFbBV9m/Screenshot-from-2021-08-25-01-40-59.png)
I spend more than 4 hrs trying to figure the problem where it's coming from I couldn't know the problem it's coming from the Aliases because from the start I was using aliases and everything was working good so I decide to rebuild everything hoping to figure what I was adding can be the problem so every time I add something I check if Partial Hydration work till I add the aliases and importing the react component with.

and I'm sorry for my bad English I know I make so many mistakes hope my explanation was clear.

### Steps to Reproduce

1. [access] Not Found: /_astro/src/layouts/$components/Hero/index.js

**Comment by natemoo-re** [comment] 2021-09-22 18:20
Closing as a duplicate of https://github.com/snowpackjs/astro/issues/574

**Closed by natemoo-re** 2021-09-22 18:20 UTC
Labels: compiler-v2
