### ISSUE TITLE
💡 RFC: Support Deno as a runtime?

### ISSUE THREAD

**Issue by jasikpark** [snowpackjs/astro#971] opened 2021-07-31 22:28 UTC
What would it take to support Deno as a runtime for Astro? I'm not 100% sure what that would mean for people who want to use it, but I imagine that'd be by running the compiler via Deno rather than Node?

**Comment by mash-graz** [comment] 2021-08-01 04:30
i already asked for deno support in #566 , because i really try to avoid node based software on my servers.

snowpack resp. pika played a tremendous important role for deno, because it was the first available solution to repack npm packages in ESM as needed by deno. i therefore think, that you will hardly find anywhere more experienced developers for this kind of job. even the fundamental design ideas of astro -- the focus on isolated islands of component modules and their distribution -- look close related to this role in history and denos consequent utilization of ESM. an adaption of astro for deno, probably even as the main runtime, would therefore make a lot of sense to me.

but on the other hand we have to face the fact, that hardly any significant software was able to archive parallel support for deno and node until now. the gap between both worlds shouldn't be underestimated. all ports of software from node to deno needed so much rework, that the results in most cases don't have much in common with the origin anymore.

until now there is no SSG available in deno, which comes close to the fascinating promises of astro. 

although there are some nice solutions around - like [lume](https://lumeland.github.io/), a kind of 11ty clone --, nothing available looks really exciting to me until now. i personally would anytime prefer a deno based alternative, if it would satisfy my needs. well -- in fact i would even more appreciate something written in clean and trustworthy rust, but for web related tasks it's in practice nearly unavoidable to utilize at least a minimum of javascript as well. and it's also very nice, if the resulting software looks very modular end extendable, and not like an immovable monolith, like for example [zola](https://www.getzola.org/).

astro on deno could indeed fill this gap! -- although i'm a little bit skeptic right now, if it will not also end in a big mess of ugly java script hacks of rather moderate code quality like many similar projects... ;)

**Comment by matthewp** [comment] 2021-08-02 13:19
Dupe of #566

**Closed by matthewp** 2021-08-02 13:19 UTC
