### ISSUE TITLE
Svelte component errors when importing `onMount` in `ts` mode

### ISSUE THREAD

**Issue by zephraph** [snowpackjs/astro#403] opened 2021-06-12 04:15 UTC
When running this svelte component

```svelte
<script lang="ts">
  import { onMount } from "svelte";
  onMount(() => {});
</script>

<h1>Hi</h1>
```

I'm getting 

```
ReferenceError: exports is not defined
    at eval (/_astro/src/components/LogoScene.svelte.js:8:24)
    at Object.$$render (/_snowpack/pkg/svelte.internal.v3.38.2.js:1286:18)
    at eval (/_snowpack/pkg/@astrojs.renderer-svelte.server.v0.1.0.js:10:104)
    at $$render (/_snowpack/pkg/svelte.internal.v3.38.2.js:1286:18)
    at Object.render (/_snowpack/pkg/svelte.internal.v3.38.2.js:1294:20)
    at Object.renderToStaticMarkup (/_snowpack/pkg/@astrojs.renderer-svelte.server.v0.1.0.js:25:24)
    at eval (/_snowpack/pkg/astro.dist.internal.__astro_component.v0.13.1.js:93:35)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

I do have typescript installed locally. Removing the `lang="ts"` resolves the error.

Versions:
- astro: 0.13.1
- typescript: 4.3.2

## Update

This turned out to be a TypeScript issue, and not an Astro bug. Creating this file in your project seems to solve the issue for most people:

```
{
    "moduleResolution": "node"
}
```

**Comment by tony-sull** [comment] 2021-06-13 19:14
I haven't tried TS with Svelte in astro yet so I'm flying a bit blind, but do you have `svelte-preprocess` hooked up?

That package is used for TS and other precompiler support in Svelte components - in SvelteKit that's configured in a `svelte.config.js` file.  If Svelte config isn't supported yet in Astro that'll probably be the best way to allow Svelte configuration that mimics the usual Svelte workflow.

**Comment by tony-navillus** [comment] 2021-06-13 20:31
> I haven't tried TS with Svelte in astro yet so I'm flying a bit blind, but do you have `svelte-preprocess` hooked up?
> 
> That package is used for TS and other precompiler support in Svelte components - in SvelteKit that's configured in a `svelte.config.js` file. If Svelte config isn't supported yet in Astro that'll probably be the best way to allow Svelte configuration that mimics the usual Svelte workflow.

I was actually able to get this hooked up on an Astro project but it took a bit of guess and check to find the right mix of SvelteKit's typescript config and the [Snowpack's template](https://github.com/snowpackjs/snowpack/tree/main/create-snowpack-app/app-template-svelte-typescript) for Svelte + Typescript.

[Check here](https://github.com/Navillus-BV/navillus-dev/commit/5af09e1d5f7b7d7c8e290d0b0be43199b9faefa2) for my commit to see what NPM dependencies and config files I needed if you're curious, hopefully it won't be too big of a deal to have this out of the box since it's mainly wiring up the config through Snowpack

**Comment by zephraph** [comment] 2021-06-14 14:49
Thanks for the tip! Yeah, that makes sense. I’ll try that out shortly.

**Comment by FredKSchott** [comment] 2021-06-15 05:23
Sounds like something that we may be able to enable in the svelte renderer and/or snowpack plugin.

**Comment by drwpow** [comment] 2021-06-16 20:48
@zephraph do you have a reproducable project with your full config? With the default Astro setup I’m seeing `onMount` work as expected with `lang="ts"`, even correctly executing `onMount` with `<MyComponent:load>`.

**Comment by FredKSchott** [comment] 2021-06-21 05:48
@zephraph closing as fixed, but if anyone is still seeing this issue please post and we can reopen / revisit

**Comment by zephraph** [comment] 2021-06-22 20:27
Sorry for the delay! Need to get a better handle on my GitHub notifications. 😄. 

I haven't tested it with the latest build but I'll check it out. Hopefully it's all fixed up. Thanks!

**Comment by allanvobraun** [comment] 2021-07-31 22:43
Same issue with any type of import #969.
Reopening.

**Comment by matthewp** [comment] 2021-08-02 14:52
@allanvobraun Thanks for the repro! https://github.com/allanvobraun/pernonal-site.git

**Comment by 0ql** [comment] 2021-08-12 15:41
Found a Fix:

This seems to be an issue on how typescript is configured by default.
Adding a `tsconfig.json` with:
``` json
{
  "compilerOptions": {
    "module": "ES2015",
    "target": "es5"
  }
}
```
at the project root has removed all issues I had.

Hope this helps.

**Comment by allanvobraun** [comment] 2021-08-12 17:00
> Interesting! If someone could add this to the `framework-svelte` example, that would be great. Actually, we should probably add it to all example projects now that @matthewp is making progress on the VSCode extension's TS support. Technically, every Astro project has TS support!
> 
> I wonder if we could also give renderers a `pre-check` hook check for something like this ahead of time, and give the user a helpful warning.

This setting cannot be added inside the astro by default?

**Comment by 0ql** [comment] 2021-08-12 17:18
Have the PR for the exmple ready though there might be a more elegant solution to this problem.

**Comment by nilskjQL** [comment] 2021-08-12 19:48
I tried adding the mentioned tsconfig.json but those compiler options throws some other warnings/errors in whole another Solid-JS component (in VSC):

The Solid typescript component head:
```
/** @jsxImportSource solid-js */
import {Component, For} from "solid-js"
...
```
> Cannot find module 'solid-js'. Did you mean to set the 'moduleResolution' option to 'node', or to add aliases to the 'paths' option?ts(2792)

Also dunno if related with the import, but this makes something not right with the JSX for the Solid-component. shows this on my button onClick-handlers:
```
Type '{ onClick: () => void; }' is not assignable to type 'HTMLProps<HTMLButtonElement>'.
  Property 'onClick' does not exist on type 'HTMLProps<HTMLButtonElement>'. Did you mean 'onclick'?

```

But, if I delete the contents and only keep an **empty tsconfig.json** both the Svelte and Solid component seems to work without any errors!

**Comment by FredKSchott** [comment] 2021-08-12 21:05
I think that makes sense! Astro adopts Node's moduleResolution, so adding `"moduleResolution": "node"` in all of these starter tsconfig files makes sense. Even in the svelte template, I bet you'd see that error the second you add an import.

> Type '{ onClick: () => void; }' is not assignable to type 'HTMLProps'.
> Property 'onClick' does not exist on type 'HTMLProps'. Did you mean 'onclick'?

I'm not sure! I haven't actually used Solid myself yet. Does anyone else know which capitalization is preferred for Solid? Can this be looked up?

**Comment by nilskjQL** [comment] 2021-08-13 07:34
Ah I see, instead of having an empty file, only have this in my tsconfig it seems to work:
```
{
    "moduleResolution": "node"
}
```
This seems to solves this issue as well for both Svelte and Solid component, and no squigglies on my onClicks (seems it actually imports solid-js properly now I suppose. Solids JSX is very close to React/Preact and uses camelCase for handlers (but there are some minor differences such as you can use `class` instead of `classNames` etc). Additional imports in my Svelte component resolves properly as well with this 👍

**Comment by FredKSchott** [comment] 2021-08-13 16:47
Nice! We should really add this to all `examples/*` projects, since Astro itself supports typescript. If someone could create a PR to do that, I'd consider this issue closed!

**Comment by jasikpark** [comment] 2021-09-08 21:45
> Nice! We should really add this to all `examples/*` projects, since Astro itself supports typescript. If someone could create a PR to do that, I'd consider this issue closed!

Closing this as #1108 did so! :D

**Closed by jasikpark** 2021-09-08 21:45 UTC
