### ISSUE TITLE
🐛 Tailwind Directive File Persists on Build

### ISSUE THREAD

**Issue by mrbrianhinton** [snowpackjs/astro#473] opened 2021-06-16 20:02 UTC
### Bug Report: Quick Checklist

- [x] I am on the latest version of Astro & all plugins.
- [x] I am on an ESM Node.js version: **v16.0.0+**
- [x] I use package manager: **NPM**
- [x] I run Astro on OS: **Mac OS Big Sur**

### Describe the bug

As the title states following the guidelines outlined: https://github.com/snowpackjs/astro/blob/main/docs/styling.md#-tailwind I'm adding a public/styles.css with the Tailwind Directives. On build the file is copied to the /dist with the Directives intact. I do see that Astro is creating a common-256hx1.css file with the Tailwind styles.

### Steps to reproduce

1. Working project to reference can be found: https://github.com/mrbrianhinton/takamoto-blog
2. Clone, and open project
3. `npm I` to install dependencies
3.  `npm run build` to build the project
4.  Review the /dist folder as described above

### Expected behavior

I'd expect that the public structure remains the same, and the styles.css is where the Tailwind styles are created as is typical for those using a project involving Tailwind. I can see this workflow being a bit confusing. The Directives should be removed, and the Tailwind styles added to the styles.css folder.

### Anything else?

I can see creating separate scoped stylesheets for specific components, and pages when style tags are present. BUT I also personally think that it might be nice to have the option to bundle everything into a single styles.css.

**Comment by FredKSchott** [comment] 2021-06-17 05:56
This is actually a limitation of Snowpack, but one that we want to remove and finally can now that we have a better idea of your application. 

Rough outline of what I'd like to see:
- `public/` is for raw assets, maybe built (scss -> css) and minified but not tree-shaken or bundled.
- `src/` is for your application, and any JS/CSS inside of it is bundled, tree-shaken, etc.

This is a Snowpack limitation because it's so flexible that it doesn't know if a CSS/JS file is a part of the application (can be bundled and original file removed) or is referenced directly via something like a `link` or `script` tag.

**Comment by FredKSchott** [comment] 2021-06-17 06:02
Duplicate of #454

**Closed by FredKSchott** 2021-06-17 06:02 UTC
