### ISSUE TITLE
🐛 BUG: JS files should be valid React/Preact components

### ISSUE THREAD

**Issue by RafidMuhymin** [snowpackjs/astro#1008] opened 2021-08-04 13:57 UTC
### What package manager are you using?

yarn

### What operating system are you using?

Windows

### Describe the Bug

Well, I don't know if it's a bug or not but by asking in the support chatroom in the discord channel, I get to know that JS files were treated as valid React/Preact components in the previous Astro versions. But I found that only JSX files are valid React/Preact components in Astro. I think JS files should also be supported. Because as a new Astronaut (I don't know what will you call me?!), it took me more than an hour to figure out the issue.

### Steps to Reproduce

1. Try to Iimport a .js React/Preact component
2. Error! Describe what went wrong (and what was expected instead)...
[executing astro] Error: Parse error @:4:32
    at parse (I:\travel-guru\node_modules\snowpack\node_modules\es-module-lexer\dist\lexer.cjs:1:402)
    at scanCodeImportsExports (I:\travel-guru\node_modules\snowpack\lib\cjs\rewrite-imports.js:21:29)
    at transformEsmImports (I:\travel-guru\node_modules\snowpack\lib\cjs\rewrite-imports.js:37:27)
    at Object.transformFileImports (I:\travel-guru\node_modules\snowpack\lib\cjs\rewrite-imports.js:108:16)
    at FileBuilder.resolveImports (I:\travel-guru\node_modules\snowpack\lib\cjs\build\file-builder.js:116:48)
    at async Object.loadUrl (I:\travel-guru\node_modules\snowpack\lib\cjs\commands\dev.js:640:39)
    at async load (I:\travel-guru\node_modules\snowpack\lib\cjs\commands\dev.js:217:28)
    at async I:\travel-guru\node_modules\snowpack\lib\cjs\ssr-loader\index.js:60:28
    at async I:\travel-guru\node_modules\snowpack\lib\cjs\ssr-loader\index.js:83:23
    at async initializeModule (I:\travel-guru\node_modules\snowpack\lib\cjs\ssr-loader\index.js:88:39)
    at async Object.importModule (I:\travel-guru\node_modules\snowpack\lib\cjs\ssr-loader\index.js:166:25)
    at async load (file:///I:/travel-guru/node_modules/astro/dist/runtime.js:76:17)
    at async Server.<anonymous> (file:///I:/travel-guru/node_modules/astro/dist/dev.js:21:20) {
  idx: 98
}
3. Snowpack should parse fine without any error

**Comment by drwpow** [comment] 2021-08-16 23:09
I think this is a documentation issue. Ideally, we’d like to enforce that React **always** requires `.jsx` or `.tsx` syntax. The fact that earlier Astro versions partially-handled React seems to be more of a quirk than intentional behavior. But that said, documentation and error messages should be improved so that you have a better idea of what’s wrong going forward.

**Comment by FredKSchott** [comment] 2021-11-19 18:45
Thanks for the report! We believe that this has been fixed in astro v0.21, going out today. Let us know if you can still reproduce the issue after updating to v0.21 and we'll be happy to take a look.

**Closed by FredKSchott** 2021-11-19 18:45 UTC
