### ISSUE TITLE
🐛 BUG: Hot reload does not update Svelte components' styling

### ISSUE THREAD

**Issue by MatsDahlin** [snowpackjs/astro#641] opened 2021-07-09 06:51 UTC
### What package manager are you using?

npm

### What operating system are you using?

OSX Big Sur

### Describe the Bug

When using standard Svelte styling using `<style>` tags in components, hot reloading is not working correctly.
Instead of applying the changed styles, hot reload removes all styles from the Svelte component.

### Steps to Reproduce

1. `npm init astro` using any template
2. cd to initiated directory
3. `npm install`
4. Create a Test.svelte file in components/
5. Create a basic svelte component in Test.svelte:
```svelte
<p>This is styled Svelte</p>
<style>
p {
 font-size: 2rem;
 font-weight: 600;
 color: purple;
}
</style>
```
6. Add component to any Astro page.
7. run `npm start`
8. visit the page that you added the component to
9. it should render fine
10. change any of the CSS in the <style> tag in the Test.svelte component.
11. Notice browser window is reloading
12. **error**: The svelte component is no longer styled, it has a class applied, but no styling.
13. **expected**: The svelte component should have been updated with the new styling
14. If you now go and manually refresh the page in browser, the correct styling should be rendered again.

**Comment by natemoo-re** [comment] 2021-07-09 16:54
Closing as a duplicate of #635.

**Closed by natemoo-re** 2021-07-09 16:54 UTC
