### ISSUE TITLE
💡 RFC: Publish VS Code extension to the Open VSX Registry

### ISSUE THREAD

**Issue by mikenikles** [snowpackjs/astro#739] opened 2021-07-18 17:04 UTC
### Background & Motivation

I want to be able to use the Astro VS Code extension in open source VS Code editors, such as www.gitpod.io.

### Possible solutions

The [`open-vsx/publish-extensions`](https://github.com/open-vsx/publish-extensions) repository contains instructions on [how to add a new extension](https://github.com/open-vsx/publish-extensions#how-to-add-an-extension) to the Open VSX Registry.

### Alternatives considered

N/A

### Risks, downsides, and/or tradeoffs

Minimal risk or downsides. Once configured, the process is fully automated and new releases of the Astro VS Code extension will be published to the Open VSX Registry automatically every day.

### Detailed Design

I'll definitely open a PR for the `open-vsx/publish-extensions` repo, but need some guidance on how to create the `.vsix` file.

### Help make it happen!

- [ ] I am willing to submit a PR to implement this change.
- [X] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by jasikpark** [comment] 2021-07-18 19:16
Duplicate of #685 xD See yah over there

**Closed by jasikpark** 2021-07-18 19:16 UTC

**Comment by mikenikles** [comment] 2021-07-18 19:18
Omg... You opened that 5 days ago and I didn't even catch it when I looked at the open issues 😅.

Note to self: Use the search functionality...
