### ISSUE TITLE
🐛 BUG: unused class names added

### ISSUE THREAD

**Issue by janimo** [snowpackjs/astro#1448] opened 2021-09-28 14:20 UTC
### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

In a newly generated project with an empty 
<style>
</style>

block added to the only page, a new class is generated and set on most elements in the HTML even if it is not declared or needed.
It does not happen with <style></style> (on a single line)

Having unused class names generated is a bit confusing.

### Steps to Reproduce

1. `npm init astro` using template <NAME>
2. Add an empty style block to the page
3. launch the page and look at the source
5. There are unused astro-XXXXXX classes sprinkled in the source.

**Comment by jasikpark** [comment] 2021-09-28 14:36
This is a duplicate of https://github.com/snowpackjs/astro/issues/1295, thanks for the bug report though! I'm going to close this, please continue in #1295

**Closed** 2021-09-28 14:36 UTC
