### ISSUE TITLE
🐛 BUG: Error: Unexpected token ' . ' on `node@12`

### ISSUE THREAD

**Issue by dELUSION-MS** [snowpackjs/astro#627] opened 2021-07-08 10:18 UTC
### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

Whenever I init a project with React template and try to start dev server or build It always shows **parse-error** Unexpected token ' . '. And then neither does dev server shows anything but Unexpected token ' . ' nor build gives any output.

### Steps to Reproduce

1. npm init astro
2. Choose a template
3.  Choose React
4. npm install
5. npm start
6. Error: [parse-error] Unexpected token ' . '

**Comment by natemoo-re** [comment] 2021-07-08 16:04
Thanks for the report, I'm taking a look at this!

**Comment by natemoo-re** [comment] 2021-07-08 17:13
Hmm, having trouble reproducing this.

What `npm` and `node` versions are you using and/or would you mind sharing a reproduction?

**Comment by dELUSION-MS** [comment] 2021-07-08 17:33
I am using `npm` v7.5.2 and `nodejs` v12.21.0.

![image](https://user-images.githubusercontent.com/58584472/124965593-eeddb200-e03f-11eb-933f-cf6c6f87047c.png)
Then in the dev server - 
![image](https://user-images.githubusercontent.com/58584472/124965758-1b91c980-e040-11eb-80dd-1351bb3e7001.png)
And at console - 
![image](https://user-images.githubusercontent.com/58584472/124965911-40863c80-e040-11eb-9dbe-3e6178316ca4.png)
also with the build command - 
![image](https://user-images.githubusercontent.com/58584472/124966057-6f9cae00-e040-11eb-8d21-5cd69d7957db.png)

**Comment by natemoo-re** [comment] 2021-07-08 20:26
I narrowed this down to `node@12`. Seems to work on `node@14`!

I'll keep this open to make sure we investigate further, but hopefully upgrading Node will unblock you for now?

**Comment by dELUSION-MS** [comment] 2021-07-08 20:35
Seems like upgrading to `node`@14 solved the issue. Thank you!

**Comment by gjactat** [comment] 2021-07-16 15:04
Hello,

I've also met this error (nodejs v12). Seems to be related to the **optional chaining** feature which is indeed [only supported in nodejs 14](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining#browser_compatibility) and used in [this file](https://github.com/snowpackjs/astro/blob/5814f2faca2a4b7a9d00f2895fe824ac786e6383/packages/astro/src/compiler/index.ts#L143) :
```js
  const Astro = {
    props,
    site: new URL('/', ${JSON.stringify(site)}),
    css: props[__astroInternal]?.css || [],
    request: props[__astroInternal]?.request || {},
    isPage: props[__astroInternal]?.isPage || false
  };
```
Hence, the Unexpected token '.' because of **?.css** (same goes for **?.request** and **?.isPage**)... And probably some others lines in the product (optional chaining is **so handy** !).
Hope this helps.

**Comment by FredKSchott** [comment] 2021-07-20 21:42
Fixed in https://github.com/snowpackjs/astro/pull/752

**Closed by FredKSchott** 2021-07-20 21:42 UTC
