### ISSUE TITLE
Renderer's  List not updated unless node modules is deleted.

### ISSUE THREAD

**Issue by Hanawa02** [snowpackjs/astro#414] opened 2021-06-13 09:46 UTC
**Astro version:** 0.13.1

Steps to test: 
- clone this [repo](https://github.com/Hanawa02/astro-docs/tree/error-vue-preact) **_or_** Init an Astro Docs project (comes by default with preact renderer)
- run npm install
- run npm start
- at this point, it should work fine
- add the Vue renderer to `astro.config.mjs`
- if you **didn't** clone the [repo](https://github.com/Hanawa02/astro-docs/tree/error-vue-preact): create a simple vue component
- re run the app
- It should display an error similart to:
```
Error: [object Object] is not a valid HTML tag name in <[object Object] innerHTML>
    at x (/_snowpack/pkg/preact-render-to-string.v5.1.19.js:5:3869)
    at Object.m [as default] (/_snowpack/pkg/preact-render-to-string.v5.1.19.js:5:1063)
    at Object.renderToStaticMarkup (/_snowpack/pkg/@astrojs.renderer-preact.server.v0.1.0.js:16:26)
    at eval (/_snowpack/pkg/astro.dist.internal.astro_component.v0.13.1.js:90:35)
    at async Promise.all (index 0)
    at Object.h (/_snowpack/pkg/astro.dist.internal.h.v0.13.1.js:41:20)
    at async Promise.all (index 0)
    at Object.h (/_snowpack/pkg/astro.dist.internal.h.v0.13.1.js:41:20)
    at async Promise.all (index 1)
    at Object.h (/_snowpack/pkg/astro.dist.internal.h.v0.13.1.js:41:20)
    at async Promise.all (index 1)
    at Object.h (/_snowpack/pkg/astro.dist.internal.h.v0.13.1.js:41:20)
    at Object.renderToStaticMarkup (/_snowpack/pkg/astro.dist.internal.astro_component.v0.13.1.js:26:16)
    at eval (/_snowpack/pkg/astro.dist.internal.astro_component.v0.13.1.js:90:20)
    at async Promise.all (index 0)
    at Object.h (/_snowpack/pkg/astro.dist.internal.h.v0.13.1.js:41:20)
    at Object.renderPage (/_astro/pages/website/index.astro.js:38:27)
    at load (file:///D:/Dev/astro-docs/node_modules/astro/src/runtime.ts:207:17)
    at Server.<anonymous> (file:///D:/Dev/astro-docs/node_modules/astro/src/dev.ts:33:20)
```

Workaround/Fix: Whenever you add a new renderer (if you run npm install before), delete the node modules (npm ci doesn't work), run npm install, and npm run start.

@natemoo-re

**Comment by matthewp** [comment] 2021-06-14 14:54
Another work around is run the `--reload` command which clears the build cache:

```
astro --reload
```

---

The root cause here is that the renderer is built by the snowpack plugin. How do you inform Snowpack that a file needs to be rebuilt when it changes @FredKSchott ?

**Comment by FredKSchott** [comment] 2021-06-14 15:07
remind me, is the issue that we're injecting code into `astro/dist/internal/h` based on your config? Then this error makes sense (Snowpack bases a ton on the fact that npm packages are static)

We should talk about how we could move any auto-generated files into Astro's runtime (and out of `astro/dist`). That way, Astro would build it fresh on every startup.

**Comment by matthewp** [comment] 2021-06-14 15:10
Rebuild on startup is an improvement but people might expect it to rebuild without restarting the dev server as well.

**Comment by FredKSchott** [comment] 2021-06-14 15:30
+1, but right now we don't have any "restart on config change" behavior so that feels like a separate enhancement

**Comment by matthewp** [comment] 2021-06-14 15:37
Just tested and confirmed that marking that file with `markedChanged` in the config does not trigger a rebuild. So I guess moving this file outside of the astro package might be required here.

**Comment by FredKSchott** [comment] 2021-06-14 15:44
yea that makes sense, we are breaking a really core Snowpack assumption here so it would be good to do regardless

**Comment by matthewp** [comment] 2021-06-16 14:40
We discussed fixing this by moving the `__astro_component` outside of the astro package and making it be imported through snowpack. This won't work because Astro components in npm packages can't depend on URLs like this. 

---

My current idea is to make this module no longer be dynamically created. Instead, have it export a setter function, something like:

```js
export function setRenderers(rendererSources, renderers) {
  __rendererSources = rendererSources;
  __renderers = renderers;
}
```

Something like that. The runtime can this call this function any time the config file changes, which updates the renderers.

**Comment by matthewp** [comment] 2021-06-16 17:56
Started working on this here: https://github.com/snowpackjs/astro/compare/dynamic-renderers?expand=1 (this is for me so I don't forget the branch name)

**Comment by FredKSchott** [comment] 2021-06-17 07:22
Oh thats really clever 🧠 . If it works, ship it!

**Closed** 2021-06-21 12:44 UTC
Labels: bug
