### ISSUE TITLE
🐛 BUG: Markdown files don't work if you change the configs pages directory

### ISSUE THREAD

**Issue by okikio** [snowpackjs/astro#1174] opened 2021-08-20 14:34 UTC
### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

I tried to setup astro pages in a `docs/` directory, but no matter what I do I get this error,
```bash
[executing astro] CompileError: Could not find "/docs/index.md.js"
    at load (file:///workspaces/native/node_modules/.pnpm/astro@0.19.1_typescript@4.4.1-rc/node_modules/astro/dist/runtime.js:164:16)
    at async Server.<anonymous> (file:///workspaces/native/node_modules/.pnpm/astro@0.19.1_typescript@4.4.1-rc/node_modules/astro/dist/dev.js:21:20) {
  start: { line: 1, column: 0, character: 0 },
  end: undefined,
  filename: '/workspaces/native/docs/index.astro',
  frame: '1: \n   ^'
}
```

My astro config looks like this,
```ts
export default {
    // projectRoot: '.',     // Where to resolve all URLs relative to. Useful if you have a monorepo project.
    pages: './docs', // Path to Astro components, pages, and data
    // dist: './dist',       // When running `astro build`, path to final static output
    // public: './public',   // A folder of static files Astro will copy to the root. Useful for favicons, images, and other files that don’t need processing.
    buildOptions: {
      site: 'https://okikio.github.io/native',  // Your public domain, e.g.: https://my-site.dev/. Used to generate sitemaps and canonical URLs.
      // sitemap: true,      // Generate sitemap (set to "false" to disable)
    },
    devOptions: {
      // port: 3000,         // The port to run the dev server on.
      tailwindConfig: './tailwind.config.cjs', // Path to tailwind.config.js if used, e.g. './tailwind.config.js'
    },
    renderers: ['@astrojs/renderer-solid'],
  };
```

The one thing I noticed is that astro messes up the mount folder,
```bash
> astro dev

[15:21:48] [snowpack] Hint: run "snowpack init" to create a project config file. Using defaults...
[15:21:48] [snowpack] config.mount[/workspaces/native/src]: mounted directory does not exist.
[15:21:48] [snowpack] Ready!
[15:21:48] [snowpack] watching for file changes... 
[dev server] Server started in 826ms.
[dev server] Local: http://localhost:3000/
```

The one fix I have found is to not change the pages dir. or to setup snowpack with a different mount dir., this behavior is not well explained nor does the documentation cover the relationship between snowpack mounted files, and the pages dir.

### Steps to Reproduce

1. `pnpm i astro@^0.19.1 @astrojs/renderer-solid@^0.1.0 -D`
2. `mkdir docs`
3. Create an `astro.config.mjs` with 
```ts
export default {
    // projectRoot: '.',     // Where to resolve all URLs relative to. Useful if you have a monorepo project.
    pages: './docs', // Path to Astro components, pages, and data
    // dist: './dist',       // When running `astro build`, path to final static output
    // public: './public',   // A folder of static files Astro will copy to the root. Useful for favicons, images, and other files that don’t need processing.
    buildOptions: {
      site: 'https://okikio.github.io/native',  // Your public domain, e.g.: https://my-site.dev/. Used to generate sitemaps and canonical URLs.
      // sitemap: true,      // Generate sitemap (set to "false" to disable)
    },
    devOptions: {
      // port: 3000,         // The port to run the dev server on.
      tailwindConfig: './tailwind.config.cjs', // Path to tailwind.config.js if used, e.g. './tailwind.config.js'
    },
    renderers: ['@astrojs/renderer-solid'],
  };
```
4. `cd docs && echo "## index.md" > index.md`
5. `astro dev`
6. Error! I would just expect the change in the pages dir. to work.
> _**Note**: you have to open [http://localhost:3000](http://localhost:3000) in the browser for the error to appear._
```bash
[executing astro] CompileError: Could not find "/docs/index.md.js"
    at load (file:///workspaces/native/node_modules/.pnpm/astro@0.19.1_typescript@4.4.1-rc/node_modules/astro/dist/runtime.js:164:16)
    at async Server.<anonymous> (file:///workspaces/native/node_modules/.pnpm/astro@0.19.1_typescript@4.4.1-rc/node_modules/astro/dist/dev.js:21:20) {
  start: { line: 1, column: 0, character: 0 },
  end: undefined,
  filename: '/workspaces/native/docs/index.astro',
  frame: '1: \n   ^'
}
```

**Comment by okikio** [comment] 2021-08-30 13:37
Would it be possible to setup astro to use a separate `src/` folder, e.g. `docs/`, in some of my more complex projects I find, the src folder isnt very accurate and it causes some confusion

**Comment by okikio** [comment] 2021-08-31 18:07
This issue is related to #674

**Comment by jonasmerlin** [comment] 2021-09-01 09:12
> Thanks @itday !
> 
> I think the underlying issue here is that the `src` option in the config is required. You should be able to have a pages folder at the top-level, but `src` is still required. I added a src folder to your example but the bug still happens, so that's not the issue.
> 
> My guess is that the problem is we do not mount the pages folder:
> 
> https://github.com/snowpackjs/astro/blob/290f203279eecd590371412aad637a5a673ce604/packages/astro/src/runtime.ts#L286-L290
> 
> We should mount the folder if it is not a subfolder of `src`.

Actually, with those mounts, not even the custom `src/` is working. I ran into this the other day and found that the change in  PR #1272 makes the custom `src/` work at least. Though not yet the custom `pages/` (custom `pages/` needs to be set though, but it needs to be inside the custom `src/`)

**Comment by jonasmerlin** [comment] 2021-09-01 09:31
But I just tested that adding the following third mount makes it possible to move the `pages/` directory outside the `src/`. (The docs imply that this should be possible.)

```
  const mountOptions = __spreadProps(__spreadValues({}, existsSync(astroConfig.public) ? {[fileURLToPath(astroConfig.public)]: {url: "/", static: true, resolve: false}} : {}), {
    [fileURLToPath(frontendPath)]: "/_astro_frontend",
    [fileURLToPath(src)]: `/_astro/${fileURLToPath(src).slice(fileURLToPath(projectRoot).length - 1)}`,
    [fileURLToPath(pages)]: `/_astro/${fileURLToPath(pages).slice(fileURLToPath(projectRoot).length - 1)}`, // new!
  });
```

**Comment by FredKSchott** [comment] 2021-11-19 18:44
Duplicate of #674

**Closed by FredKSchott** 2021-11-19 18:44 UTC
Labels: good first issue
