### ISSUE TITLE
🐛 BUG: `Astro.fetchCollection()` fails if called multiple times in the same page

### ISSUE THREAD

**Issue by tony-sull** [snowpackjs/astro#863] opened 2021-07-26 17:34 UTC
### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

Calling `Astro.fetchContent()` multiple times with different glob selectors fails the build

### Steps to Reproduce

1. clone [example repro](https://github.com/tony-sull/repro-astro-fetchContent-multiple)
2. npm install && npm build
3. Error! Build fails with an unexpected token error
4. Now comment out the second call to `fetchContent()` in `src/pages/index.astro` - build now succeeds

### Link to Minimal Reproducible Example (Optional)

https://github.com/tony-sull/repro-astro-fetchContent-multiple

**Comment by mmarkelov** [comment] 2021-07-28 09:13
I just made some research, and not sure that this is related to Astro.
For example I got this astro file:
```
let allPosts = Astro.fetchContent(import.meta.globEager("./posts/*.md"));
const a = Astro.fetchContent(import.meta.globEager("./posts/introducing-astro.md"));
```

But this transformed to unexpected result:
```js
import * as __glob__1_0 from './posts/introducing-astro.md';
import * as __glob__0_0 from './posts/introducing-astro.md';
import * as __SNOWPACK_ENV__ from '/_snowpack/env.js';
import.meta.env = __SNOWPACK_ENV__;


import fetch from 'node-fetch';
import {fetchContent} from 'astro/dist/internal/fetch-content.js';



const __TopLevelAstro = {
  site: new URL('/', "http://localhost:3000"),
  fetchContent: (globResult) => fetchContent(globResult, import.meta.url),
};
const Astro = __TopLevelAstro;





import { h, Fragment } from 'astro/dist/internal/h.js';
const __astroInternal = Symbol('astro.internal');
async function __render(props, ...children) {
  const Astro = {
    ...__TopLevelAstro,
    props,
    css: (props[__astroInternal] && props[__astroInternal].css) || [],
    request: (props[__astroInternal] && props[__astroInternal].request) || {},
    // broken result here
    isPage: (props[__astroInternal] && props[__astroInternal].{
        "./posts/introducing-astro.md": __glob__1_0
}ts = Astro.fetchContent(import.meta.globEager("./posts/*.md"));
const a = Astro.fetchContent({
        "./posts/introducing-astro.md": __glob__0_0
});

  
  return h(Fragment, null, h(Fragment, null,h("!doctype", {"html":true,}),(Astro.isPage ? h(Fragment, null, h(Fragment, null, Astro.css.map((css) => h("link", { "rel": "stylesheet", "href": css }))), h("script", {}, "window.HMR_WEBSOCKET_PORT = 12321;"), h("script", { "type": "module", "src": "/_snowpack/hmr-client.js" })) : null),h("html", {"lang":"en",},h("head", {},h("link", {"rel":"stylesheet","href":"/blog.css",})),h("body", {}))));
}
export default { isAstroComponent: true, __render };

// `__renderPage()`: Render the contents of the Astro module as a page. This is a special flow,
// triggered by loading a component directly by URL.
export async function __renderPage({request, children, props, css}) {
  const currentChild = {
    isAstroComponent: true,
    layout: typeof __layout === 'undefined' ? undefined : __layout,
    content: typeof __content === 'undefined' ? undefined : __content,
    __render,
  };

  Object.defineProperty(props, __astroInternal, {
    value: {
      request,
      css,
      isPage: true
    },
    writable: false,
    enumerable: false
  })

  const childBodyResult = await currentChild.__render(props, children);

  // find layout, if one was given.
  if (currentChild.layout) {
    return currentChild.layout({
      request,
      props: {content: currentChild.content},
      children: [childBodyResult],
    });
  }

  return childBodyResult;
};

```

Just seems like that it transformed in wrong position. But i cannot find the reason

**Comment by FredKSchott** [comment] 2021-08-25 06:23
I believe that this was fixed in 0.18.0, if you can still reproduce I will reopen!

**Comment by matthewp** [comment] 2021-10-04 13:10
Reopening, https://github.com/snowpackjs/astro/issues/1363 has a reproduction. Probably this will be fixed in `next`, keeping the issue so we can check there.

**Comment by clarkio** [comment] 2021-10-14 02:12
I'm having this same issue. Seems like the next compiler will resolve this, correct?

**Closed** 2021-11-03 17:32 UTC
Labels: compiler-v2
