### ISSUE TITLE
🐛 BUG: Pressing y on `Directory not empty. Continue?` throws an error

### ISSUE THREAD

**Issue by code913** [snowpackjs/astro#700] opened 2021-07-15 11:42 UTC
### What package manager are you using?

npm

### What operating system are you using?

Linux on replit

### Describe the Bug

I tried to initialize an astro project on my nodejs repl on replit.com. It said the current directory is not empty and whether to continue or not. I said `yes` and it crashed with an unhandled promise rejection error: `fs.promises.rm is not a function`.

I'm guessing this has something to do with replit refusing to update nodejs (the current version is 1.22.1) but according to the issue template it is supported.

### Steps to Reproduce

1. `npm init astro`
2. Press y when it says `Directory not empty. Continue?`
3. mission failed

**Comment by code913** [comment] 2021-07-15 11:43
Here's a screenshot
![image](https://user-images.githubusercontent.com/54856929/125782543-5e688316-c6f2-495c-b4c4-9631577f67e5.png)
YES I USE WINDOWS 7

**Comment by BryanPan342** [comment] 2021-07-17 04:25
This seems like a duplicate of my issue: #690 

I'm guessing replit has subdirectories in its file structure, leading to the failure because currently only running recursive without the force option. 

https://github.com/snowpackjs/astro/blob/304e1c65e67b6fa8feccf9bd998dfd996669bf1d/packages/create-astro/src/index.ts#L47

Created a PR to fix that here #729, but this might have some unforeseen consequences regarding `.vscode`, `.git`, etc.

**Comment by FredKSchott** [comment] 2021-07-20 21:26
Closing as duplicate of #690

**Closed by FredKSchott** 2021-07-20 21:26 UTC
