### ISSUE TITLE
🐛 BUG: Partial hydration requires import path with an extension

### ISSUE THREAD

**Issue by kolodziejczak-sz** [snowpackjs/astro#608] opened 2021-07-06 14:13 UTC
### What package manager are you using?

yarn

### What operating system are you using?

Windows

### Describe the Bug

Partial hydration requires import path with an extension, otherwise it won't work.

This violates the typescript rule TS2691:  `An import path cannot end with a '.tsx' extension`

### Steps to Reproduce

1. Create a tsx component
2. Import the component without extension, for example `import Component from './component';`
3. Use Partial Hydration, for example `<MyComponent:load />`
4. 404, Component not found

**Comment by jasikpark** [comment] 2021-09-08 21:39
https://github.com/microsoft/TypeScript/issues/35589#issuecomment-564644320

I believe this would be more of an RFC, rather than an immediate BUG, since requiring `.tsx | .jsx | .vue` is imperative for resolving between different component types.

Typescript has said they are intent on not rewriting imports because they want all typescript code to be copy-pasteable as javascript.. 

Deno does not have this requirement, and in fact has the same imports as Astro does: https://www.typescriptlang.org/play#example/typescript-with-deno

So I think this is something to sort out what makes the most sense!

**Comment by FredKSchott** [comment] 2021-11-19 18:39
Thanks for the report! We believe that this has been fixed in astro v0.21, going out today. Let us know if you can still reproduce the issue after updating to v0.21 and we'll be happy to take a look.

**Closed by FredKSchott** 2021-11-19 18:39 UTC
