### ISSUE TITLE
💡 RFC: Markdown Default Layout

### ISSUE THREAD

**Issue by philipp-tailor** [snowpackjs/astro#1267] opened 2021-08-29 17:37 UTC
### Background & Motivation

It would be splendid if was possible to define a default layout for `pages/**/*.md`. That would save the work of having to reference the layout `.astro` file in every markdown file's frontmatter. This would be less error-prone when there's multiple content contributors, who don't necessarily need to be aware about the different layouts.

### Possible solutions

Let's say I have:

```
src/
  layouts/
    docs.astro
    changelog/
      [version].astro
  pages/
    docs/
      intro.md
      installation.md
    changelog/
      v1dot0.md
      v1dot1.md
      v2dot0.md
 ```

Then it would be awesome, if `src/pages/docs/*.md` would make a lookup to see whether a layout of the same name exists, and use it if no `layout` frontmatter property exists. The frontmatter property `layout` could always override the fallback. Similar, for `src/pages/changelog/*.md`, the algorithm would first check for the presence of a `layout` property in the frontmatter of a markdown file, then check for a `changelog.astro`, and possibly even walk into a `src/layouts/changelog/` subfolder, where a layout could - in theory - receive dynamic parameters and output different results, similar to the file based routing.

### Alternatives considered

Allow to place a `layout.astro` in `src/pages/*` (sub)directories. This might be more explicit and easier to understand, but weakens the current folder structure separation.

### Risks, downsides, and/or tradeoffs

Higher amount of framework logic a user has to consider when naming / setting up layouts. Less explicit mapping of pages and layouts. But higher flexibility and reduced verbosity for simple use-cases.

### Help make it happen!

- [ ] I am willing to submit a PR to implement this change.
- [X] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by jasikpark** [comment] 2021-08-30 00:22
I'm going to close this as a duplicate of https://github.com/snowpackjs/astro/issues/397, but please provide your input in the ghat issue! I believe it's accepted, but not yet implemented, as @natemoo-re said on discord

**Closed** 2021-08-30 00:22 UTC

**Comment by philipp-tailor** [comment] 2021-08-30 06:29
Thank you for the de-duplication. I searched for issues with titles containing `Markdown`, which is why i hadn't seen #397.

**Comment by jasikpark** [comment] 2021-09-27 21:04
I'm not sure which column this issue should be in - it's definitely accepted, but this one is a duplicate 😅
