### ISSUE TITLE
💡 RFC: Allow to set a default layout for all posts

### ISSUE THREAD

**Issue by stenehall** [snowpackjs/astro#723] opened 2021-07-16 22:03 UTC
### Background & Motivation

Importing a set of blog posts there's a lot of extra work having to set `layout` for each post. 

It would be great if there was a posibility to set a default layout in astro.cofig.mjs

### Possible solutions

Extend `astro.config.mjs` with `defaultLayout`

### Alternatives considered

One other possible solution would be having default layout.astro files in each folder, but this seems far more complex.

### Risks, downsides, and/or tradeoffs

Added complexity. Opening up for having a default layout means the next step is having one per folder and so on. It might create unnecessary complexity.

### Open Questions

Is `astro.config.mjs` the intended place for all settings? Could we have a per folder settings file? placing a `layout.astro` file in `src/pages/posts` for example.

### Help make it happen!

- [ ] I am willing to submit a PR to implement this change.
- [X] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by L1lith** [comment] 2021-07-17 03:21
I think this is a duplicate of [this issue](https://github.com/snowpackjs/astro/issues/643)

**Comment by stenehall** [comment] 2021-07-17 08:28
> I think this is a duplicate of [this issue](https://github.com/snowpackjs/astro/issues/643)

From my understanding of what `_app.js` It’s not really meant to solve the same thing,  but definitely overlap. The app file is your general wrapper for everything. You might then want one design for pages and one design for blog posts. That’s where a default layout comes in. For the blog posts you’d not want to have to set a layout for each post.

**Comment by FredKSchott** [comment] 2021-07-20 04:17
Duplicat of #397

**Closed by FredKSchott** 2021-07-20 04:17 UTC
