### ISSUE TITLE
🐛 BUG: Build fails when importing svelte components with alias.

### ISSUE THREAD

**Issue by meigo** [snowpackjs/astro#1342] opened 2021-09-09 11:35 UTC
### What package manager are you using?

pnpm

### What operating system are you using?

Windows

### Describe the Bug

Importing svelte components with alias like: 
```
import Counter from '$components/Counter.svelte';
```
will cause a build error:
```
file:///D:/Projects/Astro/test/src/pages/index.astro: could not find "/_astro/src/pages/$components/Counter.svelte.js"
```
Alias is defined in snowpack.config.mjs:
```
export default {
  alias: {
    $components: './src/components',
	...
  },
};
```
Importing astro components with same alias works without any problems.

### Steps to Reproduce

...

**Comment by natemoo-re** [comment] 2021-09-22 14:59
Closing as a duplicate of https://github.com/snowpackjs/astro/issues/574

**Closed by natemoo-re** 2021-09-22 14:59 UTC
