### ISSUE TITLE
🐛 BUG: <Markdown content={content}> causes parse error

### ISSUE THREAD

**Issue by lhermann** [snowpackjs/astro#1259] opened 2021-08-28 20:56 UTC
### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

I am on `astro@0.20.3`

Using the markdown component works when used like this:
``` html
<Markdown>
  # Foo
</Markdown>
```

But it causes a parse error when used like in this .astro file:
``` astro
---
import { Markdown } from 'astro/components';
const content = "# Foo";
---

<Markdown content={content} />
```

Error message:
```
[23:50:59] [snowpack] Build Result Error: There was a problem with a file build result.
[executing astro] Error: Parse error @:1:1
    at parse (/client/node_modules/snowpack/node_modules/es-module-lexer/dist/lexer.cjs:1:402)
    at scanCodeImportsExports (/client/node_modules/snowpack/lib/cjs/rewrite-imports.js:21:29)
    at transformEsmImports (/client/node_modules/snowpack/lib/cjs/rewrite-imports.js:37:27)
    at Object.transformFileImports (/client/node_modules/snowpack/lib/cjs/rewrite-imports.js:108:16)
    at FileBuilder.resolveImports (/client/node_modules/snowpack/lib/cjs/build/file-builder.js:116:48)
    at async Object.loadUrl (/client/node_modules/snowpack/lib/cjs/commands/dev.js:641:39)
    at async load (/client/node_modules/snowpack/lib/cjs/commands/dev.js:217:28)
    at async /client/node_modules/snowpack/lib/cjs/ssr-loader/index.js:60:28
    at async Object.importModule (/client/node_modules/snowpack/lib/cjs/ssr-loader/index.js:165:26)
    at async load (file:///path/to/client/node_modules/astro/dist/runtime.js:93:17)
    at async Server.<anonymous> (file:///path/to/client/node_modules/astro/dist/dev.js:21:20) {
  idx: 0
}
```

### Steps to Reproduce

1. Use basic astro template
2. Create .astro file in `/src/pages` as described in this report
3. Try to open the page

**Comment by lhermann** [comment] 2021-08-28 21:28
Investigating further, the above .astro file only works, if it is the `pages/index.astro`, it seems NOT to work for any other page name for example `pages/test.astro`

**Comment by lhermann** [comment] 2021-08-29 14:07
Found a workaround
```astro
---
import PageLayout from '../layouts/MarkdownPage.astro'
import { renderMarkdown } from '@astrojs/markdown-support'

const markdownString = "# Foo Bar";
const { content } = await renderMarkdown(markdownString);
---

<PageLayout>
  {content}
</PageLayout>
```

**Comment by jthegedus** [comment] 2021-08-31 23:37
Notably, `renderMarkdown` does not separate out frontmatter from the rest of the Markdown content. I would have expected this to work in the same was as `fetchContent`

**Comment by madx** [comment] 2021-09-01 19:34
Be aware that `renderMarkdown` will not apply code highlighting properly, more details about this in #699

**Comment by jthegedus** [comment] 2021-09-02 00:24
@FredKSchott just to clarify, OP says this Bug is present on all pages EXCEPT `pages/index.astro`

**Comment by FredKSchott** [comment] 2021-09-02 03:27
whoops! That's what I meant, thanks for the correction

**Comment by lhermann** [comment] 2021-09-02 07:58
@FredKSchott let me know how I can be of help.

**Comment by tbjgolden** [comment] 2021-09-03 18:54
Hey - having the same issue. On an M1 mac if that matters.

Mine also happens on pages/index.astro however. More generally, it happens for me on any page it attempts to render onto the page - fetching the source markdown and logging it was possible but would crash when used with a Markdown component. 

I verified that it wasn't the markdown itself that was causing the issue, as a simple string of text still blew up.

**Comment by okikio** [comment] 2021-09-06 04:24
This issue might be related to #1185

**Comment by matthewp** [comment] 2021-09-30 20:06
Going to mark this as a new compiler fix as we aren't marking changes to the Markdown component in the main branch now.

**Comment by amatiasq** [comment] 2021-10-06 08:40
Duplicate of #933

**Comment by natemoo-re** [comment] 2021-11-01 18:23
Thanks @amatiasq! Closing as a duplicate.

**Closed by natemoo-re** 2021-11-01 18:23 UTC
Labels: compiler-v2
